[32mINFO    [0m integration.test_teardown:test_teardown.py:72 Scaling up by 2 units
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongodb-k8s/0 [idle] active: Primary
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongodb-k8s/0 [idle] active: Primary
  mongodb-k8s/1 [executing] active: 
  mongodb-k8s/2 [executing] active: 
[32mINFO    [0m integration.ha_tests.helpers:helpers.py:340 Unit name: mongodb-k8s/0. Target unit name: mongodb-k8s/0, True
[32mINFO    [0m integration.test_teardown:test_teardown.py:74 Scaling down by 1 units
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongodb-k8s/0 [idle] active: Primary
  mongodb-k8s/1 [idle] active: 
  mongodb-k8s/2 [idle] active: 
[32mINFO    [0m integration.ha_tests.helpers:helpers.py:340 Unit name: mongodb-k8s/0. Target unit name: mongodb-k8s/0, True
[32mINFO    [0m integration.test_teardown:test_teardown.py:74 Scaling down by 1 units
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongodb-k8s/0 [idle] active: Primary
  mongodb-k8s/1 [idle] active: 
[32mINFO    [0m integration.ha_tests.helpers:helpers.py:340 Unit name: mongodb-k8s/0. Target unit name: mongodb-k8s/0, True
[32mINFO    [0m integration.test_teardown:test_teardown.py:72 Scaling up by 2 units
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongodb-k8s/0 [idle] active: Primary
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongodb-k8s/0 [idle] active: Primary
  mongodb-k8s/1 [idle] active: 
  mongodb-k8s/2 [idle] active: 
[32mINFO    [0m integration.ha_tests.helpers:helpers.py:340 Unit name: mongodb-k8s/0. Target unit name: mongodb-k8s/0, True
[32mINFO    [0m integration.test_teardown:test_teardown.py:74 Scaling down by 2 units
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongodb-k8s/0 [idle] active: Primary
  mongodb-k8s/1 [idle] active: 
  mongodb-k8s/2 [idle] active: 
[32mINFO    [0m integration.ha_tests.helpers:helpers.py:340 Unit name: mongodb-k8s/0. Target unit name: mongodb-k8s/0, True
[32mINFO    [0m integration.test_teardown:test_teardown.py:72 Scaling up by 3 units
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongodb-k8s/0 [idle] active: Primary
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongodb-k8s/0 [idle] active: Primary
  mongodb-k8s/1 [idle] active: 
  mongodb-k8s/2 [idle] active: 
  mongodb-k8s/3 [executing] maintenance: installing charm software
[32mINFO    [0m integration.ha_tests.helpers:helpers.py:340 Unit name: mongodb-k8s/0. Target unit name: mongodb-k8s/0, True
[32mINFO    [0m integration.test_teardown:test_teardown.py:74 Scaling down by 3 units
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongodb-k8s/0 [idle] active: Primary
  mongodb-k8s/1 [idle] active: 
  mongodb-k8s/2 [idle] active: 
  mongodb-k8s/3 [idle] active: 
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongodb-k8s/0 [idle] active: Primary
[32mINFO    [0m integration.ha_tests.helpers:helpers.py:340 Unit name: mongodb-k8s/0. Target unit name: mongodb-k8s/0, True
[32mINFO    [0m integration.test_teardown:test_teardown.py:72 Scaling up by 4 units
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongodb-k8s/0 [idle] active: Primary
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongodb-k8s/0 [idle] active: Primary
  mongodb-k8s/1 [executing] active: 
  mongodb-k8s/2 [executing] active: 
  mongodb-k8s/3 [executing] maintenance: installing charm software
  mongodb-k8s/4 [executing] maintenance: installing charm software
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongodb-k8s/0 [idle] active: Primary
  mongodb-k8s/1 [idle] active: 
  mongodb-k8s/2 [idle] active: 
  mongodb-k8s/3 [idle] maintenance: installing charm software
  mongodb-k8s/4 [idle] active: 
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongodb-k8s/0 [executing] active: Primary
  mongodb-k8s/1 [idle] active: 
  mongodb-k8s/2 [idle] active: 
  mongodb-k8s/3 [executing] maintenance: installing charm software
  mongodb-k8s/4 [idle] active: 
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongodb-k8s/0 [idle] active: Primary
[32mINFO    [0m integration.ha_tests.helpers:helpers.py:340 Unit name: mongodb-k8s/0. Target unit name: mongodb-k8s/0, True
[32mINFO    [0m integration.test_teardown:test_teardown.py:74 Scaling down by 4 units
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongodb-k8s/0 [idle] active: Primary
  mongodb-k8s/1 [idle] active: 
  mongodb-k8s/2 [idle] active: 
  mongodb-k8s/3 [idle] active: 
  mongodb-k8s/4 [idle] active: 
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongodb-k8s/0 [idle] active: Primary
  mongodb-k8s/1 [executing] terminated: 
  mongodb-k8s/2 [executing] terminated: 
  mongodb-k8s/3 [executing] terminated: 
  mongodb-k8s/4 [executing] terminated: 
[32mINFO    [0m integration.ha_tests.helpers:helpers.py:340 Unit name: mongodb-k8s/0. Target unit name: mongodb-k8s/0, True
[32mINFO    [0m integration.test_teardown:test_teardown.py:72 Scaling up by 5 units
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongodb-k8s/0 [idle] active: Primary
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongodb-k8s/0 [idle] active: Primary
  mongodb-k8s/1 [executing] maintenance: installing charm software
  mongodb-k8s/2 [executing] maintenance: installing charm software
  mongodb-k8s/3 [executing] maintenance: installing charm software
  mongodb-k8s/4 [executing] maintenance: installing charm software
  mongodb-k8s/5 [executing] maintenance: installing charm software
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongodb-k8s/0 [idle] active: Primary
  mongodb-k8s/1 [idle] active: 
  mongodb-k8s/2 [executing] maintenance: installing charm software
  mongodb-k8s/3 [idle] active: 
  mongodb-k8s/4 [idle] active: 
  mongodb-k8s/5 [idle] active: 
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongodb-k8s/0 [idle] active: Primary
  mongodb-k8s/1 [idle] active: 
  mongodb-k8s/2 [idle] error: hook failed: "secret-changed"
  mongodb-k8s/3 [idle] active: 
  mongodb-k8s/4 [idle] active: 
  mongodb-k8s/5 [idle] active: 
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongodb-k8s/0 [idle] active: Primary
  mongodb-k8s/1 [idle] active: 
  mongodb-k8s/2 [idle] active: 
  mongodb-k8s/3 [idle] active: 
  mongodb-k8s/4 [idle] active: 
  mongodb-k8s/5 [idle] active: 
[32mINFO    [0m integration.ha_tests.helpers:helpers.py:340 Unit name: mongodb-k8s/0. Target unit name: mongodb-k8s/0, True
[32mINFO    [0m integration.test_teardown:test_teardown.py:74 Scaling down by 5 units
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongodb-k8s/0 [idle] active: Primary
  mongodb-k8s/1 [idle] active: 
  mongodb-k8s/2 [idle] active: 
  mongodb-k8s/3 [idle] active: 
  mongodb-k8s/4 [idle] active: 
  mongodb-k8s/5 [idle] active: 
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongodb-k8s/0 [idle] active: Primary
  mongodb-k8s/1 [executing] terminated: 
  mongodb-k8s/2 [executing] terminated: 
  mongodb-k8s/3 [executing] terminated: 
  mongodb-k8s/4 [executing] terminated: 
  mongodb-k8s/5 [executing] terminated: 
[32mINFO    [0m integration.ha_tests.helpers:helpers.py:340 Unit name: mongodb-k8s/0. Target unit name: mongodb-k8s/0, True
[32mINFO    [0m integration.test_teardown:test_teardown.py:72 Scaling up by 6 units
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongodb-k8s/0 [idle] active: Primary
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongodb-k8s/0 [executing] active: Primary
  mongodb-k8s/1 [executing] maintenance: installing charm software
  mongodb-k8s/2 [executing] maintenance: installing charm software
  mongodb-k8s/3 [executing] maintenance: installing charm software
  mongodb-k8s/4 [executing] maintenance: installing charm software
  mongodb-k8s/5 [executing] maintenance: installing charm software
  mongodb-k8s/6 [executing] maintenance: installing charm software
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongodb-k8s/0 [executing] active: Primary
  mongodb-k8s/1 [idle] active: 
  mongodb-k8s/2 [idle] active: 
  mongodb-k8s/3 [idle] active: 
  mongodb-k8s/4 [idle] active: 
  mongodb-k8s/5 [idle] active: 
  mongodb-k8s/6 [idle] active: 
[32mINFO    [0m integration.ha_tests.helpers:helpers.py:340 Unit name: mongodb-k8s/0. Target unit name: mongodb-k8s/0, True
[32mINFO    [0m integration.test_teardown:test_teardown.py:74 Scaling down by 6 units
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongodb-k8s/0 [idle] active: Primary
  mongodb-k8s/1 [idle] active: 
  mongodb-k8s/2 [idle] active: 
  mongodb-k8s/3 [idle] active: 
  mongodb-k8s/4 [idle] active: 
  mongodb-k8s/5 [idle] active: 
  mongodb-k8s/6 [idle] active: 
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongodb-k8s/0 [idle] active: Primary
  mongodb-k8s/1 [executing] terminated: 
  mongodb-k8s/2 [executing] terminated: 
  mongodb-k8s/3 [executing] terminated: 
  mongodb-k8s/4 [executing] terminated: 
  mongodb-k8s/5 [executing] terminated: 
  mongodb-k8s/6 [executing] terminated: 
[32mINFO    [0m integration.ha_tests.helpers:helpers.py:340 Unit name: mongodb-k8s/0. Target unit name: mongodb-k8s/0, True
[32mINFO    [0m integration.test_teardown:test_teardown.py:72 Scaling up by 7 units
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongodb-k8s/0 [idle] active: Primary
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongodb-k8s/0 [executing] active: Primary
  mongodb-k8s/1 [executing] maintenance: installing charm software
  mongodb-k8s/2 [executing] maintenance: installing charm software
  mongodb-k8s/3 [executing] maintenance: installing charm software
  mongodb-k8s/4 [executing] maintenance: installing charm software
  mongodb-k8s/5 [executing] maintenance: installing charm software
  mongodb-k8s/6 [executing] maintenance: installing charm software
  mongodb-k8s/7 [executing] maintenance: installing charm software
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongodb-k8s/0 [executing] active: Primary
  mongodb-k8s/1 [executing] active: 
  mongodb-k8s/2 [executing] active: 
  mongodb-k8s/3 [executing] active: 
  mongodb-k8s/4 [executing] active: 
  mongodb-k8s/5 [executing] active: 
  mongodb-k8s/6 [executing] active: 
  mongodb-k8s/7 [executing] active: 
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongodb-k8s/0 [idle] active: Primary
[32mINFO    [0m integration.ha_tests.helpers:helpers.py:340 Unit name: mongodb-k8s/0. Target unit name: mongodb-k8s/0, True
[32mINFO    [0m integration.test_teardown:test_teardown.py:74 Scaling down by 7 units
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongodb-k8s/0 [idle] active: Primary
  mongodb-k8s/1 [idle] active: 
  mongodb-k8s/2 [idle] active: 
  mongodb-k8s/3 [idle] active: 
  mongodb-k8s/4 [idle] active: 
  mongodb-k8s/5 [idle] active: 
  mongodb-k8s/6 [idle] active: 
  mongodb-k8s/7 [idle] active: 
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongodb-k8s/0 [executing] active: Primary
  mongodb-k8s/1 [executing] terminated: 
  mongodb-k8s/2 [executing] terminated: 
  mongodb-k8s/3 [executing] terminated: 
  mongodb-k8s/4 [executing] terminated: 
  mongodb-k8s/5 [executing] maintenance: cleaning up prior to charm deletion
  mongodb-k8s/6 [executing] maintenance: stopping charm software
  mongodb-k8s/7 [executing] maintenance: stopping charm software
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongodb-k8s/0 [idle] active: Primary
  mongodb-k8s/1 [executing] terminated: 
  mongodb-k8s/2 [executing] terminated: 
  mongodb-k8s/3 [executing] terminated: 
  mongodb-k8s/4 [executing] terminated: 
  mongodb-k8s/5 [executing] terminated: 
  mongodb-k8s/6 [executing] terminated: 
  mongodb-k8s/7 [executing] terminated: 
[32mINFO    [0m integration.ha_tests.helpers:helpers.py:340 Unit name: mongodb-k8s/0. Target unit name: mongodb-k8s/0, True
[32mINFO    [0m pytest_operator.plugin:plugin.py:834 Model status:

Model  Controller          Cloud/Region        Version  SLA          Timestamp
test   microk8s-localhost  microk8s/localhost  3.5.3    unsupported  01:50:40Z

App          Version  Status  Scale  Charm        Channel  Rev  Address         Exposed  Message
mongodb-k8s           active      1  mongodb-k8s             0  10.152.183.129  no       Primary

Unit            Workload  Agent  Address      Ports  Message
mongodb-k8s/0*  active    idle   10.1.136.10         Primary

[32mINFO    [0m pytest_operator.plugin:plugin.py:840 Juju error logs:

unit-mongodb-k8s-2: 01:36:29 ERROR unit.mongodb-k8s/2.juju-log mongodb-k8s/2.is_unit_in_replica_set PyMongoError=No replica set members match selector "Primary()", Timeout: 1.0s, Topology Description: <TopologyDescription id: 66d90b1c90b208931cc72753, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('mongodb-k8s-2.mongodb-k8s-endpoints', 27017) server_type: RSGhost, rtt: 0.0004896739999935562>]>
unit-mongodb-k8s-1: 01:36:54 ERROR unit.mongodb-k8s/1.juju-log mongodb-k8s/1.is_unit_in_replica_set PyMongoError=No replica set members match selector "Primary()", Timeout: 1.0s, Topology Description: <TopologyDescription id: 66d90b35894f8b871b53fb65, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('mongodb-k8s-1.mongodb-k8s-endpoints', 27017) server_type: RSGhost, rtt: 0.0004898160000266216>]>
unit-mongodb-k8s-1: 01:38:05 ERROR unit.mongodb-k8s/1.juju-log mongodb-k8s/1.is_unit_in_replica_set PyMongoError=No replica set members match selector "Primary()", Timeout: 1.0s, Topology Description: <TopologyDescription id: 66d90b7c69ed8cb535aa6295, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('mongodb-k8s-1.mongodb-k8s-endpoints', 27017) server_type: RSGhost, rtt: 0.007341328000052272>]>
unit-mongodb-k8s-1: 01:39:33 ERROR unit.mongodb-k8s/1.juju-log mongodb-k8s/1.is_unit_in_replica_set PyMongoError=No replica set members match selector "Primary()", Timeout: 1.0s, Topology Description: <TopologyDescription id: 66d90bd3cb860f8f493af3f3, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('mongodb-k8s-1.mongodb-k8s-endpoints', 27017) server_type: RSGhost, rtt: 0.004154335999942305>]>
unit-mongodb-k8s-3: 01:39:37 ERROR unit.mongodb-k8s/3.juju-log mongodb-k8s/3.is_unit_in_replica_set PyMongoError=No replica set members match selector "Primary()", Timeout: 1.0s, Topology Description: <TopologyDescription id: 66d90bd8a2f3eeb16cb245fc, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('mongodb-k8s-3.mongodb-k8s-endpoints', 27017) server_type: RSGhost, rtt: 0.001236391000020376>]>
unit-mongodb-k8s-3: 01:40:16 ERROR unit.mongodb-k8s/3.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mongodb-k8s-3/charm/./src/charm.py", line 1608, in <module>
    main(MongoDBCharm)
  File "/var/lib/juju/agents/unit-mongodb-k8s-3/charm/venv/ops/main.py", line 553, in main
    manager.run()
  File "/var/lib/juju/agents/unit-mongodb-k8s-3/charm/venv/ops/main.py", line 529, in run
    self._emit()
  File "/var/lib/juju/agents/unit-mongodb-k8s-3/charm/venv/ops/main.py", line 518, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name, self._juju_context)
  File "/var/lib/juju/agents/unit-mongodb-k8s-3/charm/venv/ops/main.py", line 139, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mongodb-k8s-3/charm/venv/ops/framework.py", line 347, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mongodb-k8s-3/charm/venv/ops/framework.py", line 853, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mongodb-k8s-3/charm/venv/ops/framework.py", line 943, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mongodb-k8s-3/charm/./src/charm.py", line 558, in _on_mongod_pebble_ready
    container.replan()
  File "/var/lib/juju/agents/unit-mongodb-k8s-3/charm/venv/ops/model.py", line 2278, in replan
    self._pebble.replan_services()
  File "/var/lib/juju/agents/unit-mongodb-k8s-3/charm/venv/ops/pebble.py", line 2131, in replan_services
    return self._services_action('replan', [], timeout, delay)
  File "/var/lib/juju/agents/unit-mongodb-k8s-3/charm/venv/ops/pebble.py", line 2228, in _services_action
    raise ChangeError(change.err, change)
ops.pebble.ChangeError: cannot perform the following tasks:
- Start service "mongod" (cannot start service: exited quickly with code 1)
----- Logs from task 1 -----
2024-09-05T01:40:16Z INFO Most recent service output:
    {"t":{"$date":"2024-09-05T01:40:16.496Z"},"s":"I",  "c":"CONTROL",  "id":5760901, "ctx":"-","msg":"Applied --setParameter options","attr":{"serverParameters":{"processUmask":{"default":63,"value":31}}}}
    {"t":{"$date":"2024-09-05T01:40:16.496Z"},"s":"F",  "c":"CONTROL",  "id":20574,   "ctx":"-","msg":"Error during global initialization","attr":{"error":{"code":38,"codeName":"FileNotOpen","errmsg":"Can't initialize rotatable log file :: caused by :: Failed to open /var/log/mongodb/mongodb.log"}}}
2024-09-05T01:40:16Z ERROR cannot start service: exited quickly with code 1
-----
unit-mongodb-k8s-3: 01:40:16 ERROR juju.worker.uniter.operation hook "mongod-pebble-ready" (via hook dispatching script: dispatch) failed: exit status 1
unit-mongodb-k8s-3: 01:40:16 ERROR juju.worker.uniter pebble poll failed for container "mongod": failed to send pebble-ready event: hook failed
unit-mongodb-k8s-3: 01:40:18 ERROR unit.mongodb-k8s/3.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mongodb-k8s-3/charm/./src/charm.py", line 1608, in <module>
    main(MongoDBCharm)
  File "/var/lib/juju/agents/unit-mongodb-k8s-3/charm/venv/ops/main.py", line 553, in main
    manager.run()
  File "/var/lib/juju/agents/unit-mongodb-k8s-3/charm/venv/ops/main.py", line 529, in run
    self._emit()
  File "/var/lib/juju/agents/unit-mongodb-k8s-3/charm/venv/ops/main.py", line 518, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name, self._juju_context)
  File "/var/lib/juju/agents/unit-mongodb-k8s-3/charm/venv/ops/main.py", line 139, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mongodb-k8s-3/charm/venv/ops/framework.py", line 347, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mongodb-k8s-3/charm/venv/ops/framework.py", line 853, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mongodb-k8s-3/charm/venv/ops/framework.py", line 943, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mongodb-k8s-3/charm/./src/charm.py", line 863, in _on_secret_changed
    self._connect_mongodb_exporter()
  File "/var/lib/juju/agents/unit-mongodb-k8s-3/charm/./src/charm.py", line 1355, in _connect_mongodb_exporter
    container.replan()
  File "/var/lib/juju/agents/unit-mongodb-k8s-3/charm/venv/ops/model.py", line 2278, in replan
    self._pebble.replan_services()
  File "/var/lib/juju/agents/unit-mongodb-k8s-3/charm/venv/ops/pebble.py", line 2131, in replan_services
    return self._services_action('replan', [], timeout, delay)
  File "/var/lib/juju/agents/unit-mongodb-k8s-3/charm/venv/ops/pebble.py", line 2228, in _services_action
    raise ChangeError(change.err, change)
ops.pebble.ChangeError: cannot perform the following tasks:
- Start service "mongod" (cannot start service: exited quickly with code 1)
----- Logs from task 1 -----
2024-09-05T01:40:18Z INFO Most recent service output:
    {"t":{"$date":"2024-09-05T01:40:18.476Z"},"s":"I",  "c":"CONTROL",  "id":5760901, "ctx":"-","msg":"Applied --setParameter options","attr":{"serverParameters":{"processUmask":{"default":63,"value":31}}}}
    {"t":{"$date":"2024-09-05T01:40:18.477Z"},"s":"F",  "c":"CONTROL",  "id":20574,   "ctx":"-","msg":"Error during global initialization","attr":{"error":{"code":38,"codeName":"FileNotOpen","errmsg":"Can't initialize rotatable log file :: caused by :: Failed to open /var/log/mongodb/mongodb.log"}}}
2024-09-05T01:40:18Z ERROR cannot start service: exited quickly with code 1
-----
unit-mongodb-k8s-3: 01:40:18 ERROR juju.worker.uniter.operation hook "secret-changed" (via hook dispatching script: dispatch) failed: exit status 1
unit-mongodb-k8s-3: 01:41:18 ERROR unit.mongodb-k8s/3.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mongodb-k8s-3/charm/./src/charm.py", line 1608, in <module>
    main(MongoDBCharm)
  File "/var/lib/juju/agents/unit-mongodb-k8s-3/charm/venv/ops/main.py", line 553, in main
    manager.run()
  File "/var/lib/juju/agents/unit-mongodb-k8s-3/charm/venv/ops/main.py", line 529, in run
    self._emit()
  File "/var/lib/juju/agents/unit-mongodb-k8s-3/charm/venv/ops/main.py", line 518, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name, self._juju_context)
  File "/var/lib/juju/agents/unit-mongodb-k8s-3/charm/venv/ops/main.py", line 139, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mongodb-k8s-3/charm/venv/ops/framework.py", line 347, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mongodb-k8s-3/charm/venv/ops/framework.py", line 853, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mongodb-k8s-3/charm/venv/ops/framework.py", line 943, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mongodb-k8s-3/charm/./src/charm.py", line 864, in _on_secret_changed
    self._connect_pbm_agent()
  File "/var/lib/juju/agents/unit-mongodb-k8s-3/charm/./src/charm.py", line 1391, in _connect_pbm_agent
    for attempt in Retrying(
  File "/var/lib/juju/agents/unit-mongodb-k8s-3/charm/venv/tenacity/__init__.py", line 443, in __iter__
    do = self.iter(retry_state=retry_state)
  File "/var/lib/juju/agents/unit-mongodb-k8s-3/charm/venv/tenacity/__init__.py", line 376, in iter
    result = action(retry_state)
  File "/var/lib/juju/agents/unit-mongodb-k8s-3/charm/venv/tenacity/__init__.py", line 418, in exc_check
    raise retry_exc.reraise()
  File "/var/lib/juju/agents/unit-mongodb-k8s-3/charm/venv/tenacity/__init__.py", line 185, in reraise
    raise self.last_attempt.result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/var/lib/juju/agents/unit-mongodb-k8s-3/charm/./src/charm.py", line 1397, in _connect_pbm_agent
    container.replan()
  File "/var/lib/juju/agents/unit-mongodb-k8s-3/charm/venv/ops/model.py", line 2278, in replan
    self._pebble.replan_services()
  File "/var/lib/juju/agents/unit-mongodb-k8s-3/charm/venv/ops/pebble.py", line 2131, in replan_services
    return self._services_action('replan', [], timeout, delay)
  File "/var/lib/juju/agents/unit-mongodb-k8s-3/charm/venv/ops/pebble.py", line 2228, in _services_action
    raise ChangeError(change.err, change)
ops.pebble.ChangeError: cannot perform the following tasks:
- Start service "mongod" (cannot start service: exited quickly with code 1)
----- Logs from task 0 -----
2024-09-05T01:41:18Z INFO Service "logrotate" already started.
----- Logs from task 1 -----
2024-09-05T01:41:18Z INFO Most recent service output:
    {"t":{"$date":"2024-09-05T01:41:18.801Z"},"s":"I",  "c":"CONTROL",  "id":5760901, "ctx":"-","msg":"Applied --setParameter options","attr":{"serverParameters":{"processUmask":{"default":63,"value":31}}}}
    {"t":{"$date":"2024-09-05T01:41:18.801Z"},"s":"F",  "c":"CONTROL",  "id":20574,   "ctx":"-","msg":"Error during global initialization","attr":{"error":{"code":2,"codeName":"BadValue","errmsg":"Could not open a file for writing at the given auditPath: /var/log/mongodb/audit.log"}}}
2024-09-05T01:41:18Z ERROR cannot start service: exited quickly with code 1
-----
unit-mongodb-k8s-3: 01:41:19 ERROR juju.worker.uniter.operation hook "secret-changed" (via hook dispatching script: dispatch) failed: exit status 1
unit-mongodb-k8s-3: 01:41:31 ERROR unit.mongodb-k8s/3.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mongodb-k8s-3/charm/./src/charm.py", line 1608, in <module>
    main(MongoDBCharm)
  File "/var/lib/juju/agents/unit-mongodb-k8s-3/charm/venv/ops/main.py", line 553, in main
    manager.run()
  File "/var/lib/juju/agents/unit-mongodb-k8s-3/charm/venv/ops/main.py", line 529, in run
    self._emit()
  File "/var/lib/juju/agents/unit-mongodb-k8s-3/charm/venv/ops/main.py", line 518, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name, self._juju_context)
  File "/var/lib/juju/agents/unit-mongodb-k8s-3/charm/venv/ops/main.py", line 139, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mongodb-k8s-3/charm/venv/ops/framework.py", line 347, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mongodb-k8s-3/charm/venv/ops/framework.py", line 853, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mongodb-k8s-3/charm/venv/ops/framework.py", line 943, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mongodb-k8s-3/charm/./src/charm.py", line 558, in _on_mongod_pebble_ready
    container.replan()
  File "/var/lib/juju/agents/unit-mongodb-k8s-3/charm/venv/ops/model.py", line 2278, in replan
    self._pebble.replan_services()
  File "/var/lib/juju/agents/unit-mongodb-k8s-3/charm/venv/ops/pebble.py", line 2131, in replan_services
    return self._services_action('replan', [], timeout, delay)
  File "/var/lib/juju/agents/unit-mongodb-k8s-3/charm/venv/ops/pebble.py", line 2228, in _services_action
    raise ChangeError(change.err, change)
ops.pebble.ChangeError: cannot perform the following tasks:
- Start service "mongod" (cannot start service: exited quickly with code 1)
----- Logs from task 1 -----
2024-09-05T01:41:31Z INFO Most recent service output:
    {"t":{"$date":"2024-09-05T01:41:31.138Z"},"s":"I",  "c":"CONTROL",  "id":5760901, "ctx":"-","msg":"Applied --setParameter options","attr":{"serverParameters":{"processUmask":{"default":63,"value":31}}}}
    {"t":{"$date":"2024-09-05T01:41:31.139Z"},"s":"F",  "c":"CONTROL",  "id":20574,   "ctx":"-","msg":"Error during global initialization","attr":{"error":{"code":2,"codeName":"BadValue","errmsg":"Could not open a file for writing at the given auditPath: /var/log/mongodb/audit.log"}}}
2024-09-05T01:41:31Z ERROR cannot start service: exited quickly with code 1
-----
unit-mongodb-k8s-3: 01:41:31 ERROR juju.worker.uniter.operation hook "mongod-pebble-ready" (via hook dispatching script: dispatch) failed: exit status 1
unit-mongodb-k8s-3: 01:41:31 ERROR juju.worker.uniter pebble poll failed for container "mongod": failed to send pebble-ready event: hook failed
unit-mongodb-k8s-1: 01:42:15 ERROR unit.mongodb-k8s/1.juju-log mongodb-k8s/1.is_unit_in_replica_set PyMongoError=No replica set members match selector "Primary()", Timeout: 1.0s, Topology Description: <TopologyDescription id: 66d90c76471c236713eea8ea, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('mongodb-k8s-1.mongodb-k8s-endpoints', 27017) server_type: RSGhost, rtt: 0.0036041500000010274>]>
unit-mongodb-k8s-3: 01:42:19 ERROR unit.mongodb-k8s/3.juju-log mongodb-k8s/3.is_unit_in_replica_set PyMongoError=No replica set members match selector "Primary()", Timeout: 1.0s, Topology Description: <TopologyDescription id: 66d90c7ab1eff35e3eeae694, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('mongodb-k8s-3.mongodb-k8s-endpoints', 27017) server_type: RSGhost, rtt: 0.0004928140000401982>]>
unit-mongodb-k8s-4: 01:42:22 ERROR unit.mongodb-k8s/4.juju-log mongodb-k8s/4.is_unit_in_replica_set PyMongoError=No replica set members match selector "Primary()", Timeout: 1.0s, Topology Description: <TopologyDescription id: 66d90c7dabb553ceb584202f, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('mongodb-k8s-4.mongodb-k8s-endpoints', 27017) server_type: RSGhost, rtt: 0.0005745439999600421>]>
unit-mongodb-k8s-1: 01:43:05 ERROR unit.mongodb-k8s/1.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mongodb-k8s-1/charm/./src/charm.py", line 1608, in <module>
    main(MongoDBCharm)
  File "/var/lib/juju/agents/unit-mongodb-k8s-1/charm/venv/ops/main.py", line 553, in main
    manager.run()
  File "/var/lib/juju/agents/unit-mongodb-k8s-1/charm/venv/ops/main.py", line 529, in run
    self._emit()
  File "/var/lib/juju/agents/unit-mongodb-k8s-1/charm/venv/ops/main.py", line 518, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name, self._juju_context)
  File "/var/lib/juju/agents/unit-mongodb-k8s-1/charm/venv/ops/main.py", line 139, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mongodb-k8s-1/charm/venv/ops/framework.py", line 347, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mongodb-k8s-1/charm/venv/ops/framework.py", line 853, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mongodb-k8s-1/charm/venv/ops/framework.py", line 943, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mongodb-k8s-1/charm/./src/charm.py", line 558, in _on_mongod_pebble_ready
    container.replan()
  File "/var/lib/juju/agents/unit-mongodb-k8s-1/charm/venv/ops/model.py", line 2278, in replan
    self._pebble.replan_services()
  File "/var/lib/juju/agents/unit-mongodb-k8s-1/charm/venv/ops/pebble.py", line 2131, in replan_services
    return self._services_action('replan', [], timeout, delay)
  File "/var/lib/juju/agents/unit-mongodb-k8s-1/charm/venv/ops/pebble.py", line 2228, in _services_action
    raise ChangeError(change.err, change)
ops.pebble.ChangeError: cannot perform the following tasks:
- Start service "mongod" (cannot start service: exited quickly with code 1)
----- Logs from task 1 -----
2024-09-05T01:43:05Z INFO Most recent service output:
    {"t":{"$date":"2024-09-05T01:43:05.385Z"},"s":"I",  "c":"CONTROL",  "id":5760901, "ctx":"-","msg":"Applied --setParameter options","attr":{"serverParameters":{"processUmask":{"default":63,"value":31}}}}
    {"t":{"$date":"2024-09-05T01:43:05.385Z"},"s":"F",  "c":"CONTROL",  "id":20574,   "ctx":"-","msg":"Error during global initialization","attr":{"error":{"code":2,"codeName":"BadValue","errmsg":"Could not open a file for writing at the given auditPath: /var/log/mongodb/audit.log"}}}
2024-09-05T01:43:05Z ERROR cannot start service: exited quickly with code 1
-----
unit-mongodb-k8s-4: 01:43:05 ERROR unit.mongodb-k8s/4.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/./src/charm.py", line 1608, in <module>
    main(MongoDBCharm)
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/main.py", line 553, in main
    manager.run()
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/main.py", line 529, in run
    self._emit()
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/main.py", line 518, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name, self._juju_context)
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/main.py", line 139, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/framework.py", line 347, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/framework.py", line 853, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/framework.py", line 943, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/./src/charm.py", line 558, in _on_mongod_pebble_ready
    container.replan()
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/model.py", line 2278, in replan
    self._pebble.replan_services()
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/pebble.py", line 2131, in replan_services
    return self._services_action('replan', [], timeout, delay)
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/pebble.py", line 2228, in _services_action
    raise ChangeError(change.err, change)
ops.pebble.ChangeError: cannot perform the following tasks:
- Start service "mongod" (cannot start service: exited quickly with code 1)
----- Logs from task 1 -----
2024-09-05T01:43:05Z INFO Most recent service output:
    {"t":{"$date":"2024-09-05T01:43:05.491Z"},"s":"I",  "c":"CONTROL",  "id":5760901, "ctx":"-","msg":"Applied --setParameter options","attr":{"serverParameters":{"processUmask":{"default":63,"value":31}}}}
    {"t":{"$date":"2024-09-05T01:43:05.491Z"},"s":"F",  "c":"CONTROL",  "id":20574,   "ctx":"-","msg":"Error during global initialization","attr":{"error":{"code":38,"codeName":"FileNotOpen","errmsg":"Can't initialize rotatable log file :: caused by :: Failed to open /var/log/mongodb/mongodb.log"}}}
2024-09-05T01:43:05Z ERROR cannot start service: exited quickly with code 1
-----
unit-mongodb-k8s-1: 01:43:05 ERROR juju.worker.uniter.operation hook "mongod-pebble-ready" (via hook dispatching script: dispatch) failed: exit status 1
unit-mongodb-k8s-1: 01:43:05 ERROR juju.worker.uniter pebble poll failed for container "mongod": failed to send pebble-ready event: hook failed
unit-mongodb-k8s-4: 01:43:05 ERROR juju.worker.uniter.operation hook "mongod-pebble-ready" (via hook dispatching script: dispatch) failed: exit status 1
unit-mongodb-k8s-4: 01:43:05 ERROR juju.worker.uniter pebble poll failed for container "mongod": failed to send pebble-ready event: hook failed
unit-mongodb-k8s-2: 01:43:06 ERROR unit.mongodb-k8s/2.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mongodb-k8s-2/charm/./src/charm.py", line 1608, in <module>
    main(MongoDBCharm)
  File "/var/lib/juju/agents/unit-mongodb-k8s-2/charm/venv/ops/main.py", line 553, in main
    manager.run()
  File "/var/lib/juju/agents/unit-mongodb-k8s-2/charm/venv/ops/main.py", line 529, in run
    self._emit()
  File "/var/lib/juju/agents/unit-mongodb-k8s-2/charm/venv/ops/main.py", line 518, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name, self._juju_context)
  File "/var/lib/juju/agents/unit-mongodb-k8s-2/charm/venv/ops/main.py", line 139, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mongodb-k8s-2/charm/venv/ops/framework.py", line 347, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mongodb-k8s-2/charm/venv/ops/framework.py", line 853, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mongodb-k8s-2/charm/venv/ops/framework.py", line 943, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mongodb-k8s-2/charm/./src/charm.py", line 558, in _on_mongod_pebble_ready
    container.replan()
  File "/var/lib/juju/agents/unit-mongodb-k8s-2/charm/venv/ops/model.py", line 2278, in replan
    self._pebble.replan_services()
  File "/var/lib/juju/agents/unit-mongodb-k8s-2/charm/venv/ops/pebble.py", line 2131, in replan_services
    return self._services_action('replan', [], timeout, delay)
  File "/var/lib/juju/agents/unit-mongodb-k8s-2/charm/venv/ops/pebble.py", line 2228, in _services_action
    raise ChangeError(change.err, change)
ops.pebble.ChangeError: cannot perform the following tasks:
- Start service "mongod" (cannot start service: exited quickly with code 1)
----- Logs from task 1 -----
2024-09-05T01:43:06Z INFO Most recent service output:
    {"t":{"$date":"2024-09-05T01:43:06.491Z"},"s":"I",  "c":"CONTROL",  "id":5760901, "ctx":"-","msg":"Applied --setParameter options","attr":{"serverParameters":{"processUmask":{"default":63,"value":31}}}}
    {"t":{"$date":"2024-09-05T01:43:06.491Z"},"s":"F",  "c":"CONTROL",  "id":20574,   "ctx":"-","msg":"Error during global initialization","attr":{"error":{"code":38,"codeName":"FileNotOpen","errmsg":"Can't initialize rotatable log file :: caused by :: Failed to open /var/log/mongodb/mongodb.log"}}}
2024-09-05T01:43:06Z ERROR cannot start service: exited quickly with code 1
-----
unit-mongodb-k8s-2: 01:43:06 ERROR juju.worker.uniter.operation hook "mongod-pebble-ready" (via hook dispatching script: dispatch) failed: exit status 1
unit-mongodb-k8s-2: 01:43:06 ERROR juju.worker.uniter pebble poll failed for container "mongod": failed to send pebble-ready event: hook failed
unit-mongodb-k8s-2: 01:43:08 ERROR unit.mongodb-k8s/2.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mongodb-k8s-2/charm/./src/charm.py", line 1608, in <module>
    main(MongoDBCharm)
  File "/var/lib/juju/agents/unit-mongodb-k8s-2/charm/venv/ops/main.py", line 553, in main
    manager.run()
  File "/var/lib/juju/agents/unit-mongodb-k8s-2/charm/venv/ops/main.py", line 529, in run
    self._emit()
  File "/var/lib/juju/agents/unit-mongodb-k8s-2/charm/venv/ops/main.py", line 518, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name, self._juju_context)
  File "/var/lib/juju/agents/unit-mongodb-k8s-2/charm/venv/ops/main.py", line 139, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mongodb-k8s-2/charm/venv/ops/framework.py", line 347, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mongodb-k8s-2/charm/venv/ops/framework.py", line 853, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mongodb-k8s-2/charm/venv/ops/framework.py", line 943, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mongodb-k8s-2/charm/./src/charm.py", line 558, in _on_mongod_pebble_ready
    container.replan()
  File "/var/lib/juju/agents/unit-mongodb-k8s-2/charm/venv/ops/model.py", line 2278, in replan
    self._pebble.replan_services()
  File "/var/lib/juju/agents/unit-mongodb-k8s-2/charm/venv/ops/pebble.py", line 2131, in replan_services
    return self._services_action('replan', [], timeout, delay)
  File "/var/lib/juju/agents/unit-mongodb-k8s-2/charm/venv/ops/pebble.py", line 2228, in _services_action
    raise ChangeError(change.err, change)
ops.pebble.ChangeError: cannot perform the following tasks:
- Start service "mongod" (cannot start service: exited quickly with code 1)
----- Logs from task 1 -----
2024-09-05T01:43:08Z INFO Most recent service output:
    {"t":{"$date":"2024-09-05T01:43:08.452Z"},"s":"I",  "c":"CONTROL",  "id":5760901, "ctx":"-","msg":"Applied --setParameter options","attr":{"serverParameters":{"processUmask":{"default":63,"value":31}}}}
    {"t":{"$date":"2024-09-05T01:43:08.452Z"},"s":"F",  "c":"CONTROL",  "id":20574,   "ctx":"-","msg":"Error during global initialization","attr":{"error":{"code":2,"codeName":"BadValue","errmsg":"Could not open a file for writing at the given auditPath: /var/log/mongodb/audit.log"}}}
2024-09-05T01:43:08Z ERROR cannot start service: exited quickly with code 1
-----
unit-mongodb-k8s-2: 01:43:08 ERROR juju.worker.uniter.operation hook "mongod-pebble-ready" (via hook dispatching script: dispatch) failed: exit status 1
unit-mongodb-k8s-2: 01:43:08 ERROR juju.worker.uniter pebble poll failed for container "mongod": failed to send pebble-ready event: hook failed
unit-mongodb-k8s-2: 01:43:10 ERROR unit.mongodb-k8s/2.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mongodb-k8s-2/charm/./src/charm.py", line 1608, in <module>
    main(MongoDBCharm)
  File "/var/lib/juju/agents/unit-mongodb-k8s-2/charm/venv/ops/main.py", line 553, in main
    manager.run()
  File "/var/lib/juju/agents/unit-mongodb-k8s-2/charm/venv/ops/main.py", line 529, in run
    self._emit()
  File "/var/lib/juju/agents/unit-mongodb-k8s-2/charm/venv/ops/main.py", line 518, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name, self._juju_context)
  File "/var/lib/juju/agents/unit-mongodb-k8s-2/charm/venv/ops/main.py", line 139, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mongodb-k8s-2/charm/venv/ops/framework.py", line 347, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mongodb-k8s-2/charm/venv/ops/framework.py", line 853, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mongodb-k8s-2/charm/venv/ops/framework.py", line 943, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mongodb-k8s-2/charm/./src/charm.py", line 863, in _on_secret_changed
    self._connect_mongodb_exporter()
  File "/var/lib/juju/agents/unit-mongodb-k8s-2/charm/./src/charm.py", line 1355, in _connect_mongodb_exporter
    container.replan()
  File "/var/lib/juju/agents/unit-mongodb-k8s-2/charm/venv/ops/model.py", line 2278, in replan
    self._pebble.replan_services()
  File "/var/lib/juju/agents/unit-mongodb-k8s-2/charm/venv/ops/pebble.py", line 2131, in replan_services
    return self._services_action('replan', [], timeout, delay)
  File "/var/lib/juju/agents/unit-mongodb-k8s-2/charm/venv/ops/pebble.py", line 2228, in _services_action
    raise ChangeError(change.err, change)
ops.pebble.ChangeError: cannot perform the following tasks:
- Start service "mongod" (cannot start service: exited quickly with code 1)
----- Logs from task 1 -----
2024-09-05T01:43:10Z INFO Most recent service output:
    {"t":{"$date":"2024-09-05T01:43:10.361Z"},"s":"I",  "c":"CONTROL",  "id":5760901, "ctx":"-","msg":"Applied --setParameter options","attr":{"serverParameters":{"processUmask":{"default":63,"value":31}}}}
    {"t":{"$date":"2024-09-05T01:43:10.361Z"},"s":"F",  "c":"CONTROL",  "id":20574,   "ctx":"-","msg":"Error during global initialization","attr":{"error":{"code":38,"codeName":"FileNotOpen","errmsg":"Can't initialize rotatable log file :: caused by :: Failed to open /var/log/mongodb/mongodb.log"}}}
2024-09-05T01:43:10Z ERROR cannot start service: exited quickly with code 1
-----
unit-mongodb-k8s-2: 01:43:10 ERROR juju.worker.uniter.operation hook "secret-changed" (via hook dispatching script: dispatch) failed: exit status 1
unit-mongodb-k8s-2: 01:44:12 ERROR unit.mongodb-k8s/2.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mongodb-k8s-2/charm/./src/charm.py", line 1608, in <module>
    main(MongoDBCharm)
  File "/var/lib/juju/agents/unit-mongodb-k8s-2/charm/venv/ops/main.py", line 553, in main
    manager.run()
  File "/var/lib/juju/agents/unit-mongodb-k8s-2/charm/venv/ops/main.py", line 529, in run
    self._emit()
  File "/var/lib/juju/agents/unit-mongodb-k8s-2/charm/venv/ops/main.py", line 518, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name, self._juju_context)
  File "/var/lib/juju/agents/unit-mongodb-k8s-2/charm/venv/ops/main.py", line 139, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mongodb-k8s-2/charm/venv/ops/framework.py", line 347, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mongodb-k8s-2/charm/venv/ops/framework.py", line 853, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mongodb-k8s-2/charm/venv/ops/framework.py", line 943, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mongodb-k8s-2/charm/./src/charm.py", line 864, in _on_secret_changed
    self._connect_pbm_agent()
  File "/var/lib/juju/agents/unit-mongodb-k8s-2/charm/./src/charm.py", line 1391, in _connect_pbm_agent
    for attempt in Retrying(
  File "/var/lib/juju/agents/unit-mongodb-k8s-2/charm/venv/tenacity/__init__.py", line 443, in __iter__
    do = self.iter(retry_state=retry_state)
  File "/var/lib/juju/agents/unit-mongodb-k8s-2/charm/venv/tenacity/__init__.py", line 376, in iter
    result = action(retry_state)
  File "/var/lib/juju/agents/unit-mongodb-k8s-2/charm/venv/tenacity/__init__.py", line 418, in exc_check
    raise retry_exc.reraise()
  File "/var/lib/juju/agents/unit-mongodb-k8s-2/charm/venv/tenacity/__init__.py", line 185, in reraise
    raise self.last_attempt.result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/var/lib/juju/agents/unit-mongodb-k8s-2/charm/./src/charm.py", line 1397, in _connect_pbm_agent
    container.replan()
  File "/var/lib/juju/agents/unit-mongodb-k8s-2/charm/venv/ops/model.py", line 2278, in replan
    self._pebble.replan_services()
  File "/var/lib/juju/agents/unit-mongodb-k8s-2/charm/venv/ops/pebble.py", line 2131, in replan_services
    return self._services_action('replan', [], timeout, delay)
  File "/var/lib/juju/agents/unit-mongodb-k8s-2/charm/venv/ops/pebble.py", line 2228, in _services_action
    raise ChangeError(change.err, change)
ops.pebble.ChangeError: cannot perform the following tasks:
- Start service "mongod" (cannot start service: exited quickly with code 1)
----- Logs from task 1 -----
2024-09-05T01:44:12Z INFO Most recent service output:
    {"t":{"$date":"2024-09-05T01:44:12.198Z"},"s":"I",  "c":"CONTROL",  "id":5760901, "ctx":"-","msg":"Applied --setParameter options","attr":{"serverParameters":{"processUmask":{"default":63,"value":31}}}}
    {"t":{"$date":"2024-09-05T01:44:12.198Z"},"s":"F",  "c":"CONTROL",  "id":20574,   "ctx":"-","msg":"Error during global initialization","attr":{"error":{"code":38,"codeName":"FileNotOpen","errmsg":"Can't initialize rotatable log file :: caused by :: Failed to open /var/log/mongodb/mongodb.log"}}}
2024-09-05T01:44:12Z ERROR cannot start service: exited quickly with code 1
-----
unit-mongodb-k8s-2: 01:44:12 ERROR juju.worker.uniter.operation hook "secret-changed" (via hook dispatching script: dispatch) failed: exit status 1
unit-mongodb-k8s-2: 01:44:24 ERROR unit.mongodb-k8s/2.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mongodb-k8s-2/charm/./src/charm.py", line 1608, in <module>
    main(MongoDBCharm)
  File "/var/lib/juju/agents/unit-mongodb-k8s-2/charm/venv/ops/main.py", line 553, in main
    manager.run()
  File "/var/lib/juju/agents/unit-mongodb-k8s-2/charm/venv/ops/main.py", line 529, in run
    self._emit()
  File "/var/lib/juju/agents/unit-mongodb-k8s-2/charm/venv/ops/main.py", line 518, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name, self._juju_context)
  File "/var/lib/juju/agents/unit-mongodb-k8s-2/charm/venv/ops/main.py", line 139, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mongodb-k8s-2/charm/venv/ops/framework.py", line 347, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mongodb-k8s-2/charm/venv/ops/framework.py", line 853, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mongodb-k8s-2/charm/venv/ops/framework.py", line 943, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mongodb-k8s-2/charm/./src/charm.py", line 558, in _on_mongod_pebble_ready
    container.replan()
  File "/var/lib/juju/agents/unit-mongodb-k8s-2/charm/venv/ops/model.py", line 2278, in replan
    self._pebble.replan_services()
  File "/var/lib/juju/agents/unit-mongodb-k8s-2/charm/venv/ops/pebble.py", line 2131, in replan_services
    return self._services_action('replan', [], timeout, delay)
  File "/var/lib/juju/agents/unit-mongodb-k8s-2/charm/venv/ops/pebble.py", line 2228, in _services_action
    raise ChangeError(change.err, change)
ops.pebble.ChangeError: cannot perform the following tasks:
- Start service "mongod" (cannot start service: exited quickly with code 1)
----- Logs from task 1 -----
2024-09-05T01:44:24Z INFO Most recent service output:
    {"t":{"$date":"2024-09-05T01:44:24.631Z"},"s":"I",  "c":"CONTROL",  "id":5760901, "ctx":"-","msg":"Applied --setParameter options","attr":{"serverParameters":{"processUmask":{"default":63,"value":31}}}}
    {"t":{"$date":"2024-09-05T01:44:24.632Z"},"s":"F",  "c":"CONTROL",  "id":20574,   "ctx":"-","msg":"Error during global initialization","attr":{"error":{"code":2,"codeName":"BadValue","errmsg":"Could not open a file for writing at the given auditPath: /var/log/mongodb/audit.log"}}}
2024-09-05T01:44:24Z ERROR cannot start service: exited quickly with code 1
-----
unit-mongodb-k8s-2: 01:44:24 ERROR juju.worker.uniter.operation hook "mongod-pebble-ready" (via hook dispatching script: dispatch) failed: exit status 1
unit-mongodb-k8s-2: 01:44:24 ERROR juju.worker.uniter pebble poll failed for container "mongod": failed to send pebble-ready event: hook failed
unit-mongodb-k8s-2: 01:45:12 ERROR unit.mongodb-k8s/2.juju-log mongodb-k8s/2.is_unit_in_replica_set PyMongoError=No replica set members match selector "Primary()", Timeout: 1.0s, Topology Description: <TopologyDescription id: 66d90d26a0fce0c8f2f04819, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('mongodb-k8s-2.mongodb-k8s-endpoints', 27017) server_type: RSGhost, rtt: 0.012600777999978163>]>
unit-mongodb-k8s-1: 01:45:13 ERROR unit.mongodb-k8s/1.juju-log mongodb-k8s/1.is_unit_in_replica_set PyMongoError=No replica set members match selector "Primary()", Timeout: 1.0s, Topology Description: <TopologyDescription id: 66d90d28a3196343ae993b6e, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('mongodb-k8s-1.mongodb-k8s-endpoints', 27017) server_type: RSGhost, rtt: 0.0036832319999575702>]>
unit-mongodb-k8s-5: 01:45:22 ERROR unit.mongodb-k8s/5.juju-log mongodb-k8s/5.is_unit_in_replica_set PyMongoError=No replica set members match selector "Primary()", Timeout: 1.0s, Topology Description: <TopologyDescription id: 66d90d316c6a28fba01f7ff4, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('mongodb-k8s-5.mongodb-k8s-endpoints', 27017) server_type: RSGhost, rtt: 0.0005924189999859664>]>
unit-mongodb-k8s-3: 01:46:11 ERROR unit.mongodb-k8s/3.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mongodb-k8s-3/charm/./src/charm.py", line 1608, in <module>
    main(MongoDBCharm)
  File "/var/lib/juju/agents/unit-mongodb-k8s-3/charm/venv/ops/main.py", line 553, in main
    manager.run()
  File "/var/lib/juju/agents/unit-mongodb-k8s-3/charm/venv/ops/main.py", line 529, in run
    self._emit()
  File "/var/lib/juju/agents/unit-mongodb-k8s-3/charm/venv/ops/main.py", line 518, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name, self._juju_context)
  File "/var/lib/juju/agents/unit-mongodb-k8s-3/charm/venv/ops/main.py", line 139, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mongodb-k8s-3/charm/venv/ops/framework.py", line 347, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mongodb-k8s-3/charm/venv/ops/framework.py", line 853, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mongodb-k8s-3/charm/venv/ops/framework.py", line 943, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mongodb-k8s-3/charm/./src/charm.py", line 558, in _on_mongod_pebble_ready
    container.replan()
  File "/var/lib/juju/agents/unit-mongodb-k8s-3/charm/venv/ops/model.py", line 2278, in replan
    self._pebble.replan_services()
  File "/var/lib/juju/agents/unit-mongodb-k8s-3/charm/venv/ops/pebble.py", line 2131, in replan_services
    return self._services_action('replan', [], timeout, delay)
  File "/var/lib/juju/agents/unit-mongodb-k8s-3/charm/venv/ops/pebble.py", line 2228, in _services_action
    raise ChangeError(change.err, change)
ops.pebble.ChangeError: cannot perform the following tasks:
- Start service "mongod" (cannot start service: exited quickly with code 1)
----- Logs from task 1 -----
2024-09-05T01:46:11Z INFO Most recent service output:
    {"t":{"$date":"2024-09-05T01:46:11.028Z"},"s":"I",  "c":"CONTROL",  "id":5760901, "ctx":"-","msg":"Applied --setParameter options","attr":{"serverParameters":{"processUmask":{"default":63,"value":31}}}}
    {"t":{"$date":"2024-09-05T01:46:11.029Z"},"s":"F",  "c":"CONTROL",  "id":20574,   "ctx":"-","msg":"Error during global initialization","attr":{"error":{"code":38,"codeName":"FileNotOpen","errmsg":"Can't initialize rotatable log file :: caused by :: Failed to open /var/log/mongodb/mongodb.log"}}}
2024-09-05T01:46:11Z ERROR cannot start service: exited quickly with code 1
-----
unit-mongodb-k8s-3: 01:46:11 ERROR juju.worker.uniter.operation hook "mongod-pebble-ready" (via hook dispatching script: dispatch) failed: exit status 1
unit-mongodb-k8s-3: 01:46:11 ERROR juju.worker.uniter pebble poll failed for container "mongod": failed to send pebble-ready event: hook failed
unit-mongodb-k8s-1: 01:47:24 ERROR unit.mongodb-k8s/1.juju-log mongodb-k8s/1.is_unit_in_replica_set PyMongoError=No replica set members match selector "Primary()", Timeout: 1.0s, Topology Description: <TopologyDescription id: 66d90dab13085d318824341d, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('mongodb-k8s-1.mongodb-k8s-endpoints', 27017) server_type: RSGhost, rtt: 0.00788581000006161>]>
unit-mongodb-k8s-2: 01:47:24 ERROR unit.mongodb-k8s/2.juju-log mongodb-k8s/2.is_unit_in_replica_set PyMongoError=No replica set members match selector "Primary()", Timeout: 1.0s, Topology Description: <TopologyDescription id: 66d90dab515b785b35e9fd4c, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('mongodb-k8s-2.mongodb-k8s-endpoints', 27017) server_type: RSGhost, rtt: 0.0009039120000124967>]>
unit-mongodb-k8s-1: 01:48:25 ERROR unit.mongodb-k8s/1.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mongodb-k8s-1/charm/./src/charm.py", line 1608, in <module>
    main(MongoDBCharm)
  File "/var/lib/juju/agents/unit-mongodb-k8s-1/charm/venv/ops/main.py", line 553, in main
    manager.run()
  File "/var/lib/juju/agents/unit-mongodb-k8s-1/charm/venv/ops/main.py", line 529, in run
    self._emit()
  File "/var/lib/juju/agents/unit-mongodb-k8s-1/charm/venv/ops/main.py", line 518, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name, self._juju_context)
  File "/var/lib/juju/agents/unit-mongodb-k8s-1/charm/venv/ops/main.py", line 139, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mongodb-k8s-1/charm/venv/ops/framework.py", line 347, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mongodb-k8s-1/charm/venv/ops/framework.py", line 853, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mongodb-k8s-1/charm/venv/ops/framework.py", line 943, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mongodb-k8s-1/charm/./src/charm.py", line 558, in _on_mongod_pebble_ready
    container.replan()
  File "/var/lib/juju/agents/unit-mongodb-k8s-1/charm/venv/ops/model.py", line 2278, in replan
    self._pebble.replan_services()
  File "/var/lib/juju/agents/unit-mongodb-k8s-1/charm/venv/ops/pebble.py", line 2131, in replan_services
    return self._services_action('replan', [], timeout, delay)
  File "/var/lib/juju/agents/unit-mongodb-k8s-1/charm/venv/ops/pebble.py", line 2228, in _services_action
    raise ChangeError(change.err, change)
ops.pebble.ChangeError: cannot perform the following tasks:
- Start service "mongod" (cannot start service: exited quickly with code 1)
----- Logs from task 1 -----
2024-09-05T01:48:25Z INFO Most recent service output:
    {"t":{"$date":"2024-09-05T01:48:25.201Z"},"s":"I",  "c":"CONTROL",  "id":5760901, "ctx":"-","msg":"Applied --setParameter options","attr":{"serverParameters":{"processUmask":{"default":63,"value":31}}}}
    {"t":{"$date":"2024-09-05T01:48:25.202Z"},"s":"F",  "c":"CONTROL",  "id":20574,   "ctx":"-","msg":"Error during global initialization","attr":{"error":{"code":2,"codeName":"BadValue","errmsg":"Could not open a file for writing at the given auditPath: /var/log/mongodb/audit.log"}}}
2024-09-05T01:48:25Z ERROR cannot start service: exited quickly with code 1
-----
unit-mongodb-k8s-1: 01:48:25 ERROR juju.worker.uniter.operation hook "mongod-pebble-ready" (via hook dispatching script: dispatch) failed: exit status 1
unit-mongodb-k8s-1: 01:48:25 ERROR juju.worker.uniter pebble poll failed for container "mongod": failed to send pebble-ready event: hook failed
unit-mongodb-k8s-1: 01:49:55 ERROR unit.mongodb-k8s/1.juju-log mongodb-k8s/1.is_unit_in_replica_set PyMongoError=No replica set members match selector "Primary()", Timeout: 1.0s, Topology Description: <TopologyDescription id: 66d90e4292f841859a90110f, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('mongodb-k8s-1.mongodb-k8s-endpoints', 27017) server_type: RSGhost, rtt: 0.013456884000106584>]>
unit-mongodb-k8s-2: 01:49:56 ERROR unit.mongodb-k8s/2.juju-log mongodb-k8s/2.is_unit_in_replica_set PyMongoError=No replica set members match selector "Primary()", Timeout: 1.0s, Topology Description: <TopologyDescription id: 66d90e43e49347ccff181cef, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('mongodb-k8s-2.mongodb-k8s-endpoints', 27017) server_type: RSGhost, rtt: 0.0016685929999766813>]>

[32mINFO    [0m pytest_operator.plugin:plugin.py:904 Forgetting main...