[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  config-server-one/0 [idle] active: 
  mongos-k8s/0 [executing] active:
[32mINFO    [0m pytest_operator.plugin:plugin.py:903 Model status:

Model  Controller          Cloud/Region        Version  SLA          Timestamp
test   microk8s-localhost  microk8s/localhost  3.5.3    unsupported  01:40:26Z

App                Version  Status   Scale  Charm        Channel  Rev  Address         Exposed  Message
config-server-one           active       1  mongodb-k8s             0  10.152.183.20   no       
mongos-k8s                  waiting      1  mongos-k8s   6/edge    17  10.152.183.78   no       installing agent
shard-one                   active       1  mongodb-k8s             1  10.152.183.161  no       

Unit                  Workload  Agent  Address      Ports  Message
config-server-one/0*  active    idle   10.1.52.138         
mongos-k8s/0*         blocked   idle   10.1.52.142         Missing relation to config-server.
shard-one/0*          active    idle   10.1.52.141         

[32mINFO    [0m pytest_operator.plugin:plugin.py:909 Juju error logs:

unit-config-server-one-0: 01:36:14 ERROR unit.config-server-one/0.juju-log config-server:6: Failed to add shard shard-one to the config server, error=OperationFailure("Authentication failed., full error: {'ok': 0.0, 'errmsg': 'Authentication failed.', 'code': 18, 'codeName': 'AuthenticationFailed', '$clusterTime': {'clusterTime': Timestamp(1729647373, 2), 'signature': {'hash': b'\\xa0\\xf5\\xcf\\x995K,ml\\xd7\\xd3h\\xee:\\xac\\xa8\\xd9\\xba\\xc4\\x92', 'keyId': 7428778703078817817}}, 'operationTime': Timestamp(1729647373, 2)}")
unit-config-server-one-0: 01:36:14 ERROR unit.config-server-one/0.juju-log config-server:6: shard-one shard does not have the same auth as the config server.
unit-mongos-k8s-0: 01:37:56 ERROR unit.mongos-k8s/0.juju-log cluster:7: mongos service is not ready yet.
unit-mongos-k8s-0: 01:38:58 ERROR unit.mongos-k8s/0.juju-log cluster:7: mongos service is not ready yet.

[32mINFO    [0m pytest_operator.plugin:plugin.py:991 Forgetting model main...