[32mINFO    [0m integration.ha_tests.helpers:helpers.py:340 Unit name: mongodb-k8s/0. Target unit name: mongodb-k8s/1, False
[32mINFO    [0m integration.ha_tests.helpers:helpers.py:340 Unit name: mongodb-k8s/1. Target unit name: mongodb-k8s/1, True
[32mINFO    [0m integration.ha_tests.helpers:helpers.py:642 Result of isolating unit from cluster is 'b'networkchaos.chaos-mesh.org/network-loss-primary created\n''
[32mINFO    [0m pytest_operator.plugin:plugin.py:834 Model status:

Model  Controller          Cloud/Region        Version  SLA          Timestamp
test   microk8s-localhost  microk8s/localhost  3.4.4    unsupported  01:36:16Z

App          Version  Status  Scale  Charm        Channel  Rev  Address         Exposed  Message
mongodb-k8s           active      3  mongodb-k8s             0  10.152.183.176  no       

Unit            Workload  Agent  Address      Ports  Message
mongodb-k8s/0   active    idle   10.1.40.143         
mongodb-k8s/1*  active    idle   10.1.40.142         
mongodb-k8s/2   active    idle   10.1.40.144         

[32mINFO    [0m pytest_operator.plugin:plugin.py:840 Juju error logs:


[32mINFO    [0m pytest_operator.plugin:plugin.py:904 Forgetting main...